apiVersion: apps/v1
kind: Deployment
metadata:
  name: battlesim-deployment
spec:
  selector:
    matchLabels:
      app: battlesim-deployment
  template:
    metadata:
      labels:
        app: battlesim-deployment
    spec:
      containers:
      - name: battlesim-deployment
        # This image need to be in a public repo.
        # $tag is substituted from envsubst shell command
        image: gcr.io/rosy-element-228200/github_duxbuse_9thagesimulator:$tag
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"

---
kind: Service
apiVersion: v1
metadata:
  name: battlesim-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: battlesim-deployment
  ports:
  - port: 80
    targetPort: 9000

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: battlesim-ingress
spec:
  backend:
    serviceName: battlesim-service
    servicePort: 80